webhook:
  port: 8443
  failurePolicy: Ignore

image:
  repository: ghcr.io/nblxa/kache
  #tag: latest
  pullPolicy: Always

resources:
  requests:
    cpu: 10m
    memory: 128Mi
  limits:
    cpu: 50m
    memory: 256Mi

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

pdb:
  enabled: true
  minAvailable: 1

certificates:
  certManager:
    enabled: true

serviceAccount:
  create: true
