name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: debian-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build image
      run: make build_arm64
